"""Summary Report Agent.

Responsibilities
----------------
* Collect findings from all upstream agents.
* Generate a structured Markdown code-review report.
* When an LLM is available, produce an executive summary and prioritised
  action list via GPT deep analysis.
* The report is the final output written to ``state["final_report"]``.
"""

from __future__ import annotations

import os
import textwrap
from datetime import datetime, timezone
from typing import Optional

from ..state import CodeReviewState

# ---------------------------------------------------------------------------
# Markdown report builder
# ---------------------------------------------------------------------------

_SEVERITY_BADGE = {
    "🚨": "critical",
    "🔴": "high / error",
    "🟡": "warning",
    "🔵": "info",
}


def _count_issues(section: Optional[str]) -> int:
    """Heuristic: count lines that start with an icon bullet."""
    if not section:
        return 0
    return sum(
        1
        for line in section.splitlines()
        if line.strip() and line.strip()[0] in ("🚨", "🔴", "🟡", "🔵", "⚪")
    )


def build_markdown_report(
    file_path: str,
    language: str,
    structure_analysis: Optional[str],
    style_issues: Optional[str],
    security_issues: Optional[str],
    executive_summary: str = "",
) -> str:
    """Assemble the final Markdown review report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    struct_count = _count_issues(structure_analysis)
    style_count = _count_issues(style_issues)
    sec_count = _count_issues(security_issues)
    total = struct_count + style_count + sec_count

    # Determine overall severity badge
    has_critical = security_issues and ("🚨" in security_issues or "[CRITICAL]" in security_issues)
    overall = "🚨 **Critical issues found**" if has_critical else (
        "🔴 **Issues found**" if total > 0 else "✅ **No issues found**"
    )

    lines = [
        f"# 🛡️ CodeGuard AI – Code Review Report",
        f"",
        f"> **File:** `{file_path}`  ",
        f"> **Language:** {language}  ",
        f"> **Reviewed at:** {now}  ",
        f"> **Overall:** {overall}",
        f"",
        f"---",
        f"",
        f"## 📊 Summary",
        f"",
        f"| Category | Issues Found |",
        f"|---|---|",
        f"| 🏗️ Structure | {struct_count} |",
        f"| 🎨 Style | {style_count} |",
        f"| 🔒 Security | {sec_count} |",
        f"| **Total** | **{total}** |",
        f"",
    ]

    if executive_summary:
        lines += [
            f"---",
            f"",
            f"## 🤖 Executive Summary (AI Analysis)",
            f"",
            executive_summary,
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"## 🏗️ Structure Analysis",
        f"",
        structure_analysis or "_No structural issues detected._",
        f"",
        f"---",
        f"",
        f"## 🎨 Style & Convention Check",
        f"",
        style_issues or "_No style issues detected._",
        f"",
        f"---",
        f"",
        f"## 🔒 Security Scan",
        f"",
        security_issues or "_No security issues detected._",
        f"",
        f"---",
        f"",
        f"*Generated by [CodeGuard AI](https://github.com/Hewang328/codeguard-ai)*",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# LLM executive summary (optional)
# ---------------------------------------------------------------------------


def _llm_executive_summary(
    code: str,
    structure: Optional[str],
    style: Optional[str],
    security: Optional[str],
) -> str:
    api_key = os.environ.get("OPENAI_API_KEY", "")
    if not api_key:
        return ""
    try:
        from langchain_openai import ChatOpenAI
        from langchain_core.messages import HumanMessage, SystemMessage

        llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
        system = SystemMessage(
            content=(
                "You are a senior software engineer writing an executive summary "
                "for a code review report. "
                "Synthesize the findings below into a brief (3-5 sentences) "
                "executive summary followed by a prioritised numbered action list. "
                "Be specific and actionable. Use Markdown."
            )
        )
        findings = "\n\n".join(
            filter(
                None,
                [
                    f"**Structure:**\n{structure}" if structure else None,
                    f"**Style:**\n{style}" if style else None,
                    f"**Security:**\n{security}" if security else None,
                ],
            )
        )
        human = HumanMessage(
            content=(
                f"Findings:\n{findings}\n\n"
                f"Code snippet:\n```\n{textwrap.shorten(code, 2000)}\n```"
            )
        )
        response = llm.invoke([system, human])
        return response.content
    except Exception:  # noqa: BLE001
        return ""


# ---------------------------------------------------------------------------
# Agent node
# ---------------------------------------------------------------------------


def summary_agent(state: CodeReviewState) -> dict:
    """LangGraph node: aggregates all findings into a Markdown report."""
    code = state.get("code", "")
    file_path = state.get("file_path", "unknown")
    language = state.get("language", "python")
    structure_analysis = state.get("structure_analysis")
    style_issues = state.get("style_issues")
    security_issues = state.get("security_issues")

    exec_summary = _llm_executive_summary(
        code, structure_analysis, style_issues, security_issues
    )

    report = build_markdown_report(
        file_path=file_path,
        language=language,
        structure_analysis=structure_analysis,
        style_issues=style_issues,
        security_issues=security_issues,
        executive_summary=exec_summary,
    )

    return {
        "final_report": report,
        "messages": [
            {
                "role": "assistant",
                "content": "[SummaryAgent] Review report generated.",
            }
        ],
    }
